### ISSUE TITLE
V4 vs V3

### ISSUE THREAD

**Issue by C45tr0** [types/sequelize#109]
I tried to update last night to the v4 typings and noticed I had to change my entire setup. Is there a reason that there is such a big difference between the v3 and v4 typings? 

Would be better to make them more inline with each other, for upgrading purposes?
Is v4 is a better setup in the long run?

**Comment by felixfbecker** [comment]
In v4 Models are classes. That has only minor impact on the library, but actually quite a big impact on the typings. There is a PR open to also nuke the Attributes in v3, but now that v4 is out I don't know if it's worth to push that further.
