### ISSUE TITLE
init() function is missing from @types/sequelize?

### ISSUE THREAD

**Issue by BruceHem** [types/sequelize#121]
class Student extends Model {}

Student.init() // <-- not working.

**Comment by felixfbecker** [comment]
Are you sure you are using the right typings? This repo definitely contains them.

**Comment by BruceHem** [comment]
Hey @felixfbecker When i use the one on npm @ types/sequelize, it doesn't have. but the one that i installed from typings has.

**Comment by BruceHem** [comment]
this is crazy, apparently i can get types definition from the following:
- npm i @types/sequelize --> this give me version 4.0.69
- npm i types/sequelize -> this give me version 4.0.0 i think this is the correct 1 (but why when i run this command it installs to node_modules/@types/sequelize eventhough there's no @ in front)
- typings install sequelize

**Comment by felixfbecker** [comment]
Because we don't have Microsoft/types-publisher#4 yet
