### ISSUE TITLE
Model.update should receive a Partial<T>

### ISSUE THREAD

**Issue by svallory** [types/sequelize#133]
Instead of receiveing `IModelAttributes` (which forces the interface to declare all fields as optional) the method should receive a `Partial<IModelAttributes>`

**Comment by felixfbecker** [comment]
What's `IEntityAttributes`?

**Comment by svallory** [comment]
Just an example of an interface defined to specify a model attributes. Oh... I see now why it didn't make sense. My message was incomplete. Look again

**Comment by felixfbecker** [comment]
I still don't understand where you get `IModelAttributes` from:

https://github.com/types/sequelize/blob/505b409dc42199abf5f0df5a9d9e86010850909f/lib/model.d.ts#L2566-L2567

**Comment by eseliger** [comment]
@svallory Are you referring to v3 typings?

**Comment by svallory** [comment]
Sorry @felixfbecker and @eseliger I have no idea where I saw an update receiving the attributes interface instead of `object`. But anyways, it could be updated to 

`update(keys: Partial<TAttributes>, options?: InstanceUpdateOptions): Promise<this>;`

Same goes for `updateAttributes`, but that's another issue. Feel free to close this one or update to the suggestion above

**Comment by felixfbecker** [comment]
Where does `TAttributes` come from?

**Comment by svallory** [comment]
@felixfbecker From here: https://github.com/types/sequelize/blob/cf3c69497821dab5817e1efec7dcd6ed9385e787/index.d.ts#L3684

@eseliger Yes, I'm talking about v3

**Comment by svallory** [comment]
Actually, I just update the package to 4.0.76 and I still see the same structure, but I couldn't find it in the repository. I can only find an `abstract class Model`

**Comment by SimonSchick** [comment]
I think you are mixing up sequelize `@types` typings with the ones here?

**Comment by svallory** [comment]
@SimonSchick I was, I though this was the repository for `@types/sequelize`. Sorry guys!
