### ISSUE TITLE
TS2503: Cannot find namespace 'ValidatorJS'

### ISSUE THREAD

**Issue by Diluka** [types/sequelize#143]
run `tsc`
TS2503: Cannot find namespace 'ValidatorJS'

**Comment by hoodsy** [comment]
@Diluka I'm getting this issue as well - how did you end up resolving this?

**Comment by louy** [comment]
I recommend switching to `@types/sequelize` and `@types/validator`

**Comment by BYScribble** [comment]
> I recommend switching to `@types/sequelize` and `@types/validator`

`@types/sequelize` used `@types/validator` already:
https://github.com/types/sequelize/blob/master/package.json#L8

**Comment by BYScribble** [comment]
@louy looks like issue here:
![image](https://user-images.githubusercontent.com/51192223/69806018-9e0ea200-11ea-11ea-9aa6-eb109ba75825.png)

after adding //@ts-ignore build went good

**Comment by wizardnet972** [comment]
Any solution?

**Comment by lookfirst** [comment]
Worked for me:

```
yarn add -D '@types/sequelize@4.28.1'
yarn add -D '@types/validator@10.11.3'
```

Anything newer and things start blowing up.

Note that I don't have a direct dependency on sequelize or validator in my tree. This is all failing because of a third party dependency. Yuck.

**Comment by BYScribble** [comment]
My solution: 
```
"dependencies": {
    "sequelize": "^4.41.0",
    "sequelize-typescript": "0.6.11",
},
"devDependencies": {
      "@types/validator": "10.11.3",
      "@types/sequelize": "^4.28.8",
}
```
For me main issue was in incompatible types.
Answer https://github.com/types/sequelize/issues/143#issuecomment-564431823 is totally right
