### ISSUE TITLE
it's necessary to execute a find operation to get models works?

### ISSUE THREAD

**Issue by dengue8830** [types/sequelize#158]
i used [this](https://github.com/types/sequelize/tree/master/test/models) example code and in my main app.ts i have this code

```
import { User } from './components/user/user';
import { Group } from './components/user/group';
import sequelize from './common/connection';
sequelize.sync({ force: true });
```

but it's not enough to create tables on database, in order to that i have to execute a find operation

```
sequelize.sync({ force: true })
    .then(x => {
        User.findAll();
    })
    .catch(error => {
        console.error(error);
    });
```

it's mandatory? must i execute a find operation for all my models?
which is the simplest way to sync all my models?

in the sequelize no typescript version it's enough with a simple import of the models

Thanks

**Comment by felixfbecker** [comment]
I don't fully understand your question? Are you saying the first example doesn't create the tables? You are missing a then/catch handler in the first example

**Comment by dengue8830** [comment]
sorry, it was an asynchronous problem, i wasn't waiting sequelize to finish and the connection got closed before sequelize creates the tables. I thought the work could finish even if i didn't wait for it. My fault
