### ISSUE TITLE
v3: BelongsToManyGetAssociationsMixin should allow FindOptions

### ISSUE THREAD

**Issue by lumaxis** [types/sequelize#86]
`BelongsToManyGetAssociationsMixinOptions` and possibly other associations mixins don't allow to pass in `FindOptions` even though this works perfectly fine.

**Comment by felixfbecker** [comment]
Still an issue?

**Comment by lumaxis** [comment]
Actually, yes. Now that we figured out a way to make these types installable directly from GitHub, I'll consider looking at this next 👍
